### ISSUE TITLE
Not Really an issue

### ISSUE THREAD

**Issue by vDolex** [mdesilva/AmazonFlexUnlimited#5]
im not sure how to do step number 3 could you explain a bit more in depth please

**Comment by mdesilva** [comment]
Hi, this step is just setting your username and password for use by the program. What were you having trouble with in particular ?

**Comment by vakovlad91** [comment]
where do you put the username and password is where im stuck.

**Comment by vakovlad91** [comment]
i probably sound really stupid but bear with me. do i set the variable up in a specific folder or in the Linux shell.

**Comment by evannatvig** [comment]
I use PyCharm to interact with python scripts, but doing some quick googling it appears to be pretty straightforward on a Linux Shell from this article on Digital Ocean, hope that helps.

https://www.digitalocean.com/community/tutorials/how-to-read-and-set-environmental-and-shell-variables-on-linux

**Comment by mdesilva** [comment]
Like step #3 says, just run `export AMZNFLEXUSERNAME=$username & export AMZNFLEXPWD=$password` in your terminal in the same folder that this program exists in and you should be good to go. You may have to do this every time you restart your terminal. Later, I'll get around to baking this into the config so that we don't need to use environment variables.

**Comment by mdesilva** [comment]
Note: Substitute `set` for `export` in Windows environments.

**Comment by nemo03** [comment]
Thank you so much, Mr. Desila. God bless you. Your code works perfectly and I made it run faster after I cythonized it
